esphome:
  name: universal-p1-port-dongle
  friendly_name: Universal P1 Port Dongle

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "universal-p1-port-dongle"
    password: "XXXXXXXXXXXX"

captive_portal:

uart:
  id: uart_p1
  baud_rate: 115200
  rx_pin: GPIO1
  rx_buffer_size: 1700

dsmr:
  request_pin: GPIO2
  request_interval: 1s
  uart_id: uart_p1
  max_telegram_length: 3000
  crc_check: True


sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: Energy Delivered Tariff 1
      state_class: total_increasing
    energy_delivered_tariff2:
      name: Energy Delivered Tariff 2
      state_class: total_increasing
    energy_returned_tariff1:
      name: Energy Returned Tariff 1
    energy_returned_tariff2:
      name: Energy Returned Tariff 2
    power_delivered:
      name: Power Delivered
    power_returned:
      name: Power Returned
    electricity_failures:
      name: Electricity Failures
    electricity_long_failures:
      name: Electricity Long Failures
    voltage_l1:
      name: Voltage L1
    voltage_l2:
      name: Voltage L2
    voltage_l3:
      name: Voltage L3
    current_l1:
      name: Current L1
    current_l2:
      name: Current L2
    current_l3:
      name: Current L3
    power_delivered_l1:
      name: Power Delivered L1
    power_delivered_l2:
      name: Power Delivered L2
    power_delivered_l3:
      name: Power Delivered L3
    power_returned_l1:
      name: Power Returned L1
    power_returned_l2:
      name: Power Returned L2
    power_returned_l3:
      name: Power Returned L3
    gas_delivered:
      name: Gas Delivered

text_sensor:
  - platform: dsmr
    identification:
      name: Identification
    p1_version:
      name: Version
    electricity_tariff:
      name: Tariff
        